// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0nTZwMBmJZr83ScYEItvkJtSGKJBH5U',
    appId: '1:558270719436:web:5c3fa6ae3e468d3a5c6969',
    messagingSenderId: '558270719436',
    projectId: 'mychat-app-65cb4',
    authDomain: 'mychat-app-65cb4.firebaseapp.com',
    storageBucket: 'mychat-app-65cb4.appspot.com',
    measurementId: 'G-VQ92VYEYZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFml86ZxJCrhZtad-YUTCtqKk_klgPjfk',
    appId: '1:558270719436:android:38f05314da64d47c5c6969',
    messagingSenderId: '558270719436',
    projectId: 'mychat-app-65cb4',
    storageBucket: 'mychat-app-65cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgxNfNuDlr78RP6YLe0P2JixaqLaHLG8',
    appId: '1:558270719436:ios:61db3906ff5f1d6a5c6969',
    messagingSenderId: '558270719436',
    projectId: 'mychat-app-65cb4',
    storageBucket: 'mychat-app-65cb4.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgxNfNuDlr78RP6YLe0P2JixaqLaHLG8',
    appId: '1:558270719436:ios:61db3906ff5f1d6a5c6969',
    messagingSenderId: '558270719436',
    projectId: 'mychat-app-65cb4',
    storageBucket: 'mychat-app-65cb4.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs0nTZwMBmJZr83ScYEItvkJtSGKJBH5U',
    appId: '1:558270719436:web:f1377385b41ca5925c6969',
    messagingSenderId: '558270719436',
    projectId: 'mychat-app-65cb4',
    authDomain: 'mychat-app-65cb4.firebaseapp.com',
    storageBucket: 'mychat-app-65cb4.appspot.com',
    measurementId: 'G-CLT6D3REYZ',
  );
}
